require:
 rubocop-rails
Documentation:
 Enabled: false
LineLength:
 Max: 99
Style/FrozenStringLiteralComment:
 Enabled: false
AllCops:
  Exclude:
   - 'bin/bundle'
   - 'config/environments/*'
   - 'db/*'
   - 'node_modules/node-sass/src/libsass/contrib/*'
   - 'node_modules/node-sass/src/libsass/*'
   - 'test/channels/application_cable/connection_test.rb'
   - 'test/test_helper.rb'
